---
- hosts: bigip_devices
  vars:
    nodes:
    - host: "10.128.20.104"
      port: "80"
    - host: "10.128.20.105"
      port: "80"
  connection: local
  gather_facts: false
  tasks:
  - name: Create Webserver Pool
    bigip_pool:
      provider: "{{ provider }}"
      name: "{{ app_name }}_pool"
      lb_method: "round-robin"
      monitors:
      - http
      - tcp
      monitor_type: and_list

  - name: Add Webserver pool members to Webserver Pool
    bigip_pool_member:
      provider: "{{ provider }}"
      pool: "{{ app_name }}_pool"
      address: "{{ item.host }}"
      port: "{{ item.port }}"
    with_items: "{{ nodes }}"

  - name: Add HTTPS virtual server
    bigip_virtual_server:
      provider: "{{ provider }}"
      name: "{{ app_name }}_443_vs"
      destination: "{{ vip_ip }}"
      port: "443"
      pool: "{{ app_name }}_pool"
      snat: Automap
      all_profiles:
        - http
        - clientssl

  - name: Add HTTP virtual server
    bigip_virtual_server:
      provider: "{{ provider }}"
      name: "{{ app_name }}_80_vs"
      destination: "{{ vip_ip }}"
      port: "80"
      snat: Automap
      all_profiles:
        - http
      all_rules:
        - "_sys_https_redirect"
